# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-17 01:31
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('detail', models.TextField()),
                ('do_date', models.DateField(default=datetime.datetime(2017, 12, 17, 1, 31, 37, 509077, tzinfo=utc))),
                ('used_machine', models.CharField(choices=[('LC', 'レーザー加工機'), ('3D', '3Dプリンタ'), ('MM', 'ミリングマシン')], max_length=2)),
                ('duration_time', models.DurationField()),
                ('requirements', models.CharField(max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
